In [2]:
import numpy as np

In [6]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

null_vector = np.zeros(10,dtype = int)
null_vector[4] = 1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [11]:
# 2.Create a vector with values ranging from 10 to 49.

ranging_vector = np.arange(10,49)
ranging_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [16]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0,9)
matrix = matrix.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
array = [1,2,0,0,4,0]
indeces_of_non_zero = np.nonzero(array)[0].tolist()
indeces_of_non_zero

[0, 1, 4]

In [32]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values

array = np.random.randint(0, 1000, size=(10, 10))
min_value = array.min()
max_value = array.max()
print('array->',array)
print('minimum value:',min_value)
print("maximum value",max_value)


array-> [[594 262 896 381 912 424 438 990 147 915]
 [328 788 457 788 235 738 372 606 165 396]
 [737 890 227 566 751 870 738 492 952 270]
 [513 279 156 816 965  73 374 615  54 486]
 [307 176 886 926 937 203 977  20 677 460]
 [326 438  84 852 899 116 338 787 225 583]
 [366 152  60 510 151 475 532 634 840 731]
 [427 767 217 751 521 635   8 917 123 992]
 [248 630 547 867 112 318 158 972 997 583]
 [ 12 258 677 760 349 470 568 796 387 267]]
minimum value: 8
maximum value 997


In [37]:
# 6. Create a random vector of size 30 and find the mean value.

random_vector = np.random.randint(0, 1000,size=30)
mean_value = random_vector.mean()
print("array",random_vector)
print("Mean value:",mean_value)

array [860 605 532 618 875  31 417 863 790  90 323 142 173 520 303  18 264 929
  29 431 882 943 370 319 598 881 272 652 571 946]
Mean value: 508.23333333333335


In [42]:
arr = np.array([1,2,3],[0,1,4])
print(arr.size)

TypeError: Field elements must be 2- or 3-tuples, got '0'